# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
reviews:
  poem: false
  high_level_summary: false
  collapse_walkthrough: true
  path_instructions:
    - path: "**/*.{js,ts,tsx,rs}"
      instructions: |
        1. No error handling.
        2. No unused imports, variables, or functions.
        3. For comments, keep it minimal. It should be about "Why", not "What".
chat:
  auto_reply: false
