version: "3"
dotenv: [".env.local"]
tasks:
  app:env:
    cmds:
      - |
          secrets=$(grep -v '^#' .env.prod | grep '=' | sed 's/"/\\"/g' | tr '\n' ' ')
          fly secrets set $secrets -a hypr-server

  py:init: POETRY_VIRTUALENVS_IN_PROJECT=true poetry install --no-cache --no-interaction --all-extras
  py:run: poetry run python3 {{.CLI_ARGS}}

  stripe: stripe listen --skip-verify --forward-to http://localhost:5000/webhook/stripe
  bacon: bacon {{.CLI_ARGS}}
