[package]
name = "whisper2"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
hypr-data = { workspace = true }
hypr-llama = { workspace = true }

dirs = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[dependencies]
whisper-rs = { git = "https://github.com/tazz4843/whisper-rs", rev = "f5ee632", features = ["metal", "tracing_backend"] }
