[package]
name = "notification"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }

[target.'cfg(target_os = "macos")'.dependencies]
block2 = "0.6.0"
objc2 = "0.6.0"
objc2-foundation = { version = "0.3.0" }
objc2-user-notifications = { version = "0.3.0" }
objc2-app-kit = { version = "0.3.0", features = ["NSWorkspace"] }
