[package]
name = "buffer"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
insta = "1.42.2"

[dependencies]
thiserror = { workspace = true }

markdown = { workspace = true }
mdast_util_to_markdown = { workspace = true }

tl = "0.7.8"
