[package]
name = "llama"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
dirs = { workspace = true }

[dependencies]
encoding_rs = "0.8.35"
llama-cpp-2 = { git = "https://github.com/utilityai/llama-cpp-rs", features = ["metal"], branch = "update-llama-cpp-2025-04-05" }

async-openai = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }

serde = { workspace = true }
thiserror = { workspace = true }
