[package]
name = "llama"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
dirs = { workspace = true }
gbnf-validator = { git = "https://github.com/fastrepl/gbnf-validator", rev = "1421aa1" }
hypr-buffer = { workspace = true }
indoc = "2.0.6"

[dependencies]
include_url_macro = { workspace = true }

encoding_rs = "0.8.35"
gbnf = "0.1.7"
llama-cpp-2 = { git = "https://github.com/utilityai/llama-cpp-rs", features = ["metal"], branch = "update-llama-cpp-2025-04-06" }

async-openai = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }

serde = { workspace = true }
thiserror = { workspace = true }
