[package]
name = "timeline"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
hypr-data = { workspace = true }
insta = "1.42.1"
serde_json = { workspace = true }

[dependencies]
hypr-listener-interface = { workspace = true }

intervaltree = "0.2.7"
serde = { workspace = true, features = ["derive"] }
specta = { workspace = true, features = ["derive"] }
