[package]
name = "aec2"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
hound = { workspace = true }

[dependencies]
aec-rs = "1.0.0"
serde = { workspace = true }
thiserror = { workspace = true }
