# https://github.com/tauri-apps/tauri-action/blob/3013cac/examples/test-build-only.yml
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps/desktop/**
      - plugins/**
  pull_request:
    branches:
      - main
    paths:
      - apps/desktop/**
      - plugins/**
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target universal-apple-darwin"
          - platform: "windows-latest"
            args: ""
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/pnpm_install
      - run: pnpm -F ui build
      - run: pnpm -r typecheck
      - run: pnpm -r test
      - uses: ./.github/actions/install_desktop_deps
        with:
          target: "linux"
      - uses: ./.github/actions/rust_install
        with:
          target: "linux"
      - run: cargo check -p desktop
