on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps/desktop/**
      - Taskfile.yaml
      - apps/docs/data/i18n.json
  pull_request:
    branches:
      - main
    paths:
      - apps/desktop/**
      - Taskfile.yaml
      - apps/docs/data/i18n.json

jobs:
  i18n:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/pnpm_install
      - uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: task i18n
      - run: |
          if [[ -n $(git status --porcelain apps/docs/data/i18n.json) ]]; then
            echo "::error::i18n data is not up-to-date. Please run 'task i18n' locally and commit the changes."
            echo "Changes detected:"
            git --no-pager diff apps/docs/data/i18n.json
            exit 1
          fi
